### ISSUE TITLE
a "raw" command to get the output of the real Unix utilities

### ISSUE THREAD

**Issue by pygy** [unconed/TermKit#12]
The main complaint about Termkit is that, sometimes, it hides information that the usual utilities display (rwx flags, for example).

A "raw" command, that calls the corresponding Unix binary and sends back its output to be displayed as monospaced text would address these concerns at little cost.

You could even perhaps add a raw mode for those times where you need to do several "low level" tasks in a row (I'm not sure this one is a good idea).

**Comment by briandealwis** [comment]
You can run the Unix commands by specifying a full path.  E.g., "/bin/ls -l"

**Comment by pygy** [comment]
Which means that you have to know where they are located. Not very practical IMO.

**Comment by unconed** [comment]
It is not intended for TermKit to hide information. This is merely a not-implemented-yet bug.

**Comment by pygy** [comment]
I'm going through my issues backlog. I suppose I can close this... Otherwise, please re-open.
