### ISSUE TITLE
socket.io missing

### ISSUE THREAD

**Issue by rays** [unconed/TermKit#13]
had to install socket.io for TermKit to work, should be added to the README

**Comment by adaprime** [comment]
Isn't socket.io included in the "Node/nodekit.js" file? 

In the readme, for step #4 (Run the NodeKit daemon: cd Node; node nodekit.js ) doesn't that run socket.io?

**Comment by rays** [comment]
I closed the window now so I dont have the history. But I instlled node via brew and installed npm, but it doesn't come with socket.io by default. when I ran "node nodekit.js" it complained that socket.io was missing. After installing socket.io via npm everything worked as it should.

## 

Ray Slakinski

**Comment by interlock** [comment]
Your node_path is likely not set. Try running this before nodekit, > export NODE_PATH=/usr/local/lib/node

**Comment by Nican** [comment]
I had the same error.
Apparently TermKit/Node/socket.io-node was an empty folder and had no cloned https://github.com/LearnBoost/Socket.IO-node.
Putting all files from Socket.IO-node has fixed the problem.

**Comment by quinn** [comment]
running

```
git submodule init && git submodule update
```

fixed this for me.

**Comment by rays** [comment]
Ahh, should be added to the readme

**Comment by Shifty0x88** [comment]
I got this the first time around because I forgot the <strong>-- recursive</strong> switch on my git command. Try this:

<pre><code>
rm -r TermKit
git clone https://github.com/unconed/TermKit.git <strong>--recursive</strong>
</code></pre>


it's because the socket.io is a link to another git repository.  Hope this helps
