### ISSUE TITLE
clear command or Apple-K for clearing window is unimplemented

### ISSUE THREAD

**Issue by jwill** [unconed/TermKit#19]
the command succeeds but returns 

"Content-Type: application/ocetet-stream

<random UTF-16 codes>"

**Comment by Marak** [comment]
I couldn't seem to figure out how to clear the screen either.

Does this feature exist or is it yet to be implemented?

**Comment by jwill** [comment]
I mean that terminal windows have a way to clear the screen and TermKit AFAIK doesn't. So it is a gap between regular term and TermKit.

**Comment by derDoc** [comment]
try typing the command 'clear'

**Comment by jwill** [comment]
Closing due to age.
