### ISSUE TITLE
Monospaced Output

### ISSUE THREAD

**Issue by twoolie** [unconed/TermKit#30]
Many unix facilities are setup to make use of a monospaced font for alignment. this breaks if the utilities are run through termkit as any output not tagged with explicit type headers is output as ugly-ass times new roman.

**Comment by hmottestad** [comment]
Helvetica would look nicer.

Maybe a feature request to have an option to show unknow formats in monospace.

**Comment by twoolie** [comment]
Monospace by default. many programs assume monospace in their output. it would be a shame to break that.

**Comment by unconed** [comment]
TermKit already uses monospace selectively. It simply needs more tweaking.
