### ISSUE TITLE
Crash on connect

### ISSUE THREAD

**Issue by f0086** [unconed/TermKit#34]
I get this error if I open the Frontend: https://gist.github.com/980548

**Comment by hmottestad** [comment]
You need to install the mime plugin. See readme file, "How to use". https://github.com/unconed/TermKit/blob/master/Readme.md

**Comment by jqr** [comment]
You may need to set your NODE_PATH:

```
export NODE_PATH="/usr/local/lib/node"
```

**Comment by f0086** [comment]
Ah, great. Works now. Thanks.
