### ISSUE TITLE
.bashrc (and others) support

### ISSUE THREAD

**Issue by djbe** [unconed/TermKit#4]
Just noticed TermKit doesn't load my .profile script.
Here's a list with an explanation of the differences in them: http://stefaanlippens.net/bashrc_and_others

**Comment by unconed** [comment]
I should emphasize that TermKit is not going to port over existing Bash practices wholesale. The goal is to break through Unix dogma.

In this case, I've never been very happy with how Bash manages its configs. The split between login and non-login shells sounds nice in theory (e.g. allowing you to carry over personal preferences when switching users), but in practice it's a free for all and the vast majority of users wouldn't know if you asked them. The fact that you need .bash_profile to manually include .bashrc just seems unnatural to me. Plus, in typical Unix fashion, the man page doesn't actually recommend any sort of usage pattern, it merely describes the literal scenarios in which each file is included, leaving you to guess.

So, I'm not going to re-implement the bash language. At best, I will include a parser to extract static environment variables from it, but I would prefer having a ~/.termkit.json file instead.

**Comment by djbe** [comment]
Oh right, got that wrong then.
A termkit.json file would be nice then, but maybe place it in the preferences or app support folder like normal mac apps do?

**Comment by unconed** [comment]
Yup, will do.
