### ISSUE TITLE
ls command problems

### ISSUE THREAD

**Issue by Shifty0x88** [unconed/TermKit#44]
when using the LS command with long file/folder names, the UI breaks.

Long file/folder names causes the file/folder size to be moved to top the next column. probably a .css issue

Also no support for multiple flags/switches

ls -la does not work,

ls -a has the same problem as described above even without long file names

**Comment by djbe** [comment]
The ls -la issue is already mentioned here:
https://github.com/unconed/TermKit/issues/5
