### ISSUE TITLE
Build a repository for TermKit commands.

### ISSUE THREAD

**Issue by hach-que** [unconed/TermKit#47]
It would be nice to be able to do something like:

> > install build
> > install build-XCode

or some such system (in this case it would install the build command with support for building XCode projects from TermKit, or something like that).  I could probably set this up in terms of hosting, but obviously a discussion is needed on the requirements that commands might have (e.g. how can you do extensions of commands like shown above? are there any security considerations for installing commands on the Node.js side of things?).

**Comment by shelbyKiraM** [comment]
Homebrew based? It already uses git to store the brews.
