### ISSUE TITLE
TypeError: Property 'status' of object  after almost every command

### ISSUE THREAD

**Issue by rjo** [unconed/TermKit#54]
On a snow leopard machine with a fresh install of node and TermKit, I'm getting the following exception after almost every command I execute:

worker:  /Users/rjo/git/TermKit/Node/shell/processor.js:179
      that.status(success, object);

worker:             ^

worker:  TypeError: Property 'status' of object #<Object> is not a function
    at /Users/rjo/git/TermKit/Node/shell/processor.js:179:12
    at Object.<anonymous> (/Users/rjo/git/TermKit/Node/shell/command.js:72:14)
    at Object.exit (/Users/rjo/git/TermKit/Node/misc.js:69:14)
    at /Users/rjo/git/TermKit/Node/shell/command.js:257:10
    at /Users/rjo/git/TermKit/Node/shell/builtin/cd.js:26:5
    at /Users/rjo/git/TermKit/Node/misc.js:125:10
    at Object.<anonymous> (/Users/rjo/git/TermKit/Node/shell/builtin/cd.js:16:3)
    at /Users/rjo/git/TermKit/Node/shell/command.js:261:23
    at Timer.callback (/Users/rjo/git/TermKit/Node/misc.js:81:33)

It seems like a recent issue as the installation on my desktop seems much more stable.

**Comment by unconed** [comment]
Try the new one.

**Comment by rjo** [comment]
thanks
