### ISSUE TITLE
SSH Connection

### ISSUE THREAD

**Issue by saltyfacu** [unconed/TermKit#55]
I'm running TermKit on Snow Leopard and it will not connect to a Linux server using SSH. The first issue is that it asks for password in the Node window, I typed it but never connects. Below two screenshots: one with the command trying to connect and the other with the message asking for login in the other window.

http://cl.ly/7Rx8
http://cl.ly/7RQ0

Tell me if I can help.

Cheers!

**Comment by unconed** [comment]
SSH support is not implemented yet.
