### ISSUE TITLE
osx 10.7 - issues

### ISSUE THREAD

**Issue by miguel-negrao** [unconed/TermKit#62]
I don't know if this is osx 10.7 related or not, but I have some issues and I'm running osx 10.7:
- I had to build the app again using xcode4 in order for it do anything after being started.
- Almost all the menu bar commands will beachball the application.
- If the termkit window loses focus, the it's not possible to recover focus again, so it's not possible to write in the window...

**Comment by albertz** [comment]
What did happen after you started the brebuild app? I'm also on 10.7 and it just starts with a black screen and nothing else. I wonder if that is what you meant or some other problem.

**Comment by sneilan** [comment]
I have the same problem. I used https://github.com/Souvent22/TermKit/tree/ because it fixes https://github.com/unconed/TermKit/issues/63 
TermKit.app displays a blank screen on 10.7.1. :(

**Comment by rocketnova** [comment]
TermKit.app displays a blank screen on 10.7.1 for me too.

**Comment by sneilan** [comment]
Actually, I got it work on 10.7 by loading and compiling the project within Xcode. I ran node nodekit.js separately and ran the project and it worked. I might have done something else but I'm not sure.

**Comment by rocketnova** [comment]
I see. Thanks sneilan. I got it running too, though now I'm having trouble with some of the standards commands, like ls.

**Comment by albertz** [comment]
Same for me. Whereby I'm not sure if this is related to the app or some other problem. I made a separate bug report about this: #66

**Comment by sneilan** [comment]
NP!

Yeah, any command that doesn't have parameters doesn't work.

**Comment by sneilan** [comment]
Also, cat doesn't work correctly.

**Comment by Kjuly** [comment]
Both `ls` & `cat` not work for me either. Anyway, it's cool!

**Comment by derDoc** [comment]
I think all these errors are because the tokenizer has errors.
Since the RegExp Object is incorrectly used all over the place, like boog has already remarked, it needs to be fixed before it runs correctly.
I got it to work in 10.7.1, with ls and all.
See my pull request, that should fix it.
